# 2.27 异常

在编写代码的过程中并不是一帆风顺的，除了一些编写的错误，还有一些在运行输入时的除零异常等情况，所以我们需要去捕捉这些异常来保障程序不会崩溃。

Python中的异常由try-except\[exceptionname\]块处理。

下面我们用一个故意除零的例子来讲解一下异常：

![&#x56FE;2-139](blob:https://minghuiwu.gitbook.io/d2369b46-dc5a-46c4-a16d-a9a8097c5e4c)

我们定义了一个except\_function（）函数。在try中，我们所放的是想要执行的语句。在这里我们写了一个“10/0”的语句，这是一个故意除零的操作，会造成异常。而except就是去捕捉异常的模块。

如果发生了某一个异常，就把这个异常的具体名称放在except之后，然后就可以相应给出异常处理的代码。如果没有任何问题的话，就进入else语句。最后呢要注意：在finally里面的代码块，无论是否发生异常都会被执行。

异常的种类有很多，如果我们不知道具体的种类，可以用下图的写法来解决：

![&#x56FE;2-140](../../.gitbook/assets/image%20%2890%29.png)



## &gt; 示例代码

{% code-tabs %}
{% code-tabs-item title="1.py" %}
```python
def except_function():
    try:
        # 故意除零
        10 / 0
    except:
        print ("发生某种异常啦.")
    else:
        # 正常情况.
        print ("一切正常啦.")
        pass
    finally:
        # 无论是否发生异常都将执行最后的代码
        print ("finally必须被执行，不管有没有发生异常.")
```
{% endcode-tabs-item %}
{% endcode-tabs %}

